spring:
  application:
    name: base-info
  profiles:
    active: local
  redis:
    host: 192.168.1.110
    port: 6379
    database: 0
    timeout: 30000
server:
  port: 8090
feign:
  hystrix:
    enabled: true
#打印mybatis查询日志
logging:
  level:
    com:
      jyw:
        learn:
          base:
            mapper: debug
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000 #设置熔断超时
ribbon:
  ReadTimeout: 15000 #处理请求的超时时间，默认为10秒
  ConnectTimeout: 15000 #连接建立的超时时长，默认5秒
  MaxAutoRetries: 0               #同一台实例的最大重试次数，但是不包括首次调用，默认为1次
  MaxAutoRetriesNextServer: 0     #重试负载均衡其他实例的最大重试次数，不包括首次调用，默认为0次
  OkToRetryOnAllOperations: false #/是否对所有操作都重试，默认false
  eager-load:
    clients: base-info,jyw-learn #饥饿加载
    enabled: true
---
spring:
  profiles: local
  datasource:
    url: jdbc:mysql://localhost:3306/new_jiakao?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:8081/eureka/
    fetch-registry: true #拉取eureka注册信息
    register-with-eureka: true #
---
spring:
  profiles: uat
  datasource:
    url: jdbc:mysql://192.168.1.107:3306/jyw_learn?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
  client:
    service-url:
      #defaultZone: http://127.0.0.1:8081/eureka/,http://127.0.0.1:8082/eureka/
      defaultZone: http://192.168.1.112:8082//eureka/,http://192.168.1.111:8082/eureka,http://192.168.1.110:8082/eureka
    fetch-registry: true #拉取eureka注册信息
    register-with-eureka: true #