info:
  desp: 授权服务
server:
  port: 8082
spring:
  application:
    name: oauth
  redis:
    host: 192.168.1.110
    port: 6379
    database: 0
    timeout: 30000

feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000 #设置熔断超时
ribbon:
  ReadTimeout: 15000 #处理请求的超时时间，默认为10秒
  ConnectTimeout: 15000 #连接建立的超时时长，默认5秒
  MaxAutoRetries: 0               #同一台实例的最大重试次数，但是不包括首次调用，默认为1次
  MaxAutoRetriesNextServer: 0     #重试负载均衡其他实例的最大重试次数，不包括首次调用，默认为0次
  OkToRetryOnAllOperations: false #/是否对所有操作都重试，默认false
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:8081/eureka/
    fetch-registry: true #拉取eureka注册信息
    register-with-eureka: true #
